const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
const FETCH_POSTS_REQUEST_SUCCESS = 'FETCH_POSTS_REQUEST_SUCCESS';
const FETCH_POSTS_REQUEST_FAILED = 'FETCH_POSTS_REQUEST_FAILED';
const NEW_POST = 'NEW_POST';

export {
  FETCH_POSTS_REQUEST,
  FETCH_POSTS_REQUEST_SUCCESS,
  FETCH_POSTS_REQUEST_FAILED,
  NEW_POST
};
