const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
const FETCH_POSTS_REQUEST_SUCCESS = 'FETCH_POSTS_REQUEST_SUCCESS';
const FETCH_POSTS_REQUEST_FAILED = 'FETCH_POSTS_REQUEST_FAILED';

const NEW_POST_REQUEST = 'NEW_POST_REQUEST';
const NEW_POST_REQUEST_SUCCESS = 'NEW_POST_REQUEST_SUCCESS';
const NEW_POST_REQUEST_FAILED = 'NEW_POST_REQUEST_FAILED';

export {
  FETCH_POSTS_REQUEST,
  FETCH_POSTS_REQUEST_SUCCESS,
  FETCH_POSTS_REQUEST_FAILED,
  NEW_POST_REQUEST,
  NEW_POST_REQUEST_SUCCESS,
  NEW_POST_REQUEST_FAILED
};
